import { useMemo } from "react";
import { Autocomplete, AutocompleteItem, Avatar, Input, Textarea } from "@heroui/react";
import { IAiArtwork } from "common/models/artwork";
import usePaginatedUsers from "../../../hooks/usePaginatedUsers";
import { useGetUsersQuery } from "../../../api";
import ArtworkReveal from "../../../components/artwork/artworkReveal";
import OpenLink from "../../../components/artwork/openLink";

const EMPTY: IAiArtwork = {};
const BASE_FILTER = { discordId: { $ne: "anonymous" } };

export default function AiPanel({ ai = EMPTY, isDisabled, onChange }: AiPanelProps) {
    const { items, isLoading, search, setSearch } = usePaginatedUsers(BASE_FILTER);
    // Whoever is generating it may sit outside the page of users currently loaded, so they're fetched by id
    const { data: selectedData } = useGetUsersQuery(
        { filter: { discordId: ai.generatedBy } },
        { skip: !ai.generatedBy }
    );

    const users = useMemo(() => {
        const byId = new Map((selectedData?.items ?? []).map((user) => [user.discordId, user]));
        for (const user of items) {
            byId.set(user.discordId, user);
        }
        return [...byId.values()];
    }, [items, selectedData?.items]);

    const selected = users.find((user) => user.discordId === ai.generatedBy);

    const set = <K extends keyof IAiArtwork>(key: K, value: IAiArtwork[K]) => onChange({ ...ai, [key]: value });

    return (
        <ArtworkReveal url={ai.url} alt="Generated artwork">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <Autocomplete
                    label="Generated by"
                    isLoading={isLoading}
                    isDisabled={isDisabled}
                    items={users}
                    inputValue={selected && search.length === 0 ? selected.displayname : search}
                    onInputChange={setSearch}
                    selectedKey={ai.generatedBy ?? null}
                    onSelectionChange={(key) => {
                        setSearch("");
                        set("generatedBy", key ? String(key) : undefined);
                    }}
                >
                    {(user) => (
                        <AutocompleteItem key={user.discordId} textValue={user.displayname}>
                            <div className="flex items-center gap-2">
                                <Avatar size="sm" src={user.avatarUrl} alt={user.displayname} />
                                <span>{user.displayname}</span>
                            </div>
                        </AutocompleteItem>
                    )}
                </Autocomplete>
                <Input
                    label="Tool used"
                    placeholder="Midjourney"
                    isDisabled={isDisabled}
                    value={ai.resource ?? ""}
                    onValueChange={(value) => set("resource", value)}
                />
                <Input
                    label="Artwork link"
                    className="sm:col-span-2"
                    name="ai.url"
                    isDisabled={isDisabled}
                    value={ai.url ?? ""}
                    onValueChange={(value) => set("url", value || undefined)}
                    endContent={<OpenLink url={ai.url} label="Open artwork in a new tab" />}
                />
                <Textarea
                    label="Notes"
                    className="sm:col-span-2"
                    minRows={2}
                    isDisabled={isDisabled}
                    value={ai.notes ?? ""}
                    onValueChange={(value) => set("notes", value)}
                />
            </div>
        </ArtworkReveal>
    );
}

type AiPanelProps = {
    ai?: IAiArtwork;
    isDisabled?: boolean;
    onChange: (ai: IAiArtwork) => void;
};
