import { Input, Textarea } from "@heroui/react";
import { IAiArtwork } from "common/models/artwork";
import ArtworkReveal from "../../../components/artwork/artworkReveal";
import ExternalLinkButton from "../../../components/externalLinkButton";

const EMPTY: IAiArtwork = {};

export default function AiPanel({ ai = EMPTY, isDisabled, onChange }: AiPanelProps) {
    const set = <K extends keyof IAiArtwork>(key: K, value: IAiArtwork[K]) => onChange({ ...ai, [key]: value });

    return (
        <ArtworkReveal url={ai.url} alt="Generated artwork">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <Input
                    label="Generated by"
                    placeholder="Who generated this piece"
                    isDisabled={isDisabled}
                    value={ai.generatedBy ?? ""}
                    onValueChange={(value) => set("generatedBy", value)}
                />
                <Input
                    label="Tool used"
                    placeholder="Midjourney"
                    isDisabled={isDisabled}
                    value={ai.resource ?? ""}
                    onValueChange={(value) => set("resource", value)}
                />
                <Input
                    label="Artwork link"
                    className="sm:col-span-2"
                    name="ai.url"
                    isDisabled={isDisabled}
                    value={ai.url ?? ""}
                    onValueChange={(value) => set("url", value || undefined)}
                    endContent={<ExternalLinkButton url={ai.url} label="Open artwork in a new tab" />}
                />
                <Textarea
                    label="Notes"
                    className="sm:col-span-2"
                    minRows={2}
                    isDisabled={isDisabled}
                    value={ai.notes ?? ""}
                    onValueChange={(value) => set("notes", value)}
                />
            </div>
        </ArtworkReveal>
    );
}

type AiPanelProps = {
    ai?: IAiArtwork;
    isDisabled?: boolean;
    onChange: (ai: IAiArtwork) => void;
};
